define('constant/event', [
], function(
){
    return function(ngModule){
        ngModule
            .constant('EVENT', {
                SHOW_MAIN_MENU: 'SHOW_MAIN_MENU',
                HIDE_MAIN_MENU: 'HIDE_MAIN_MENU',
                SHOW_THUMBNAIL_CREATE_FORM: 'SHOW_THUMBNAIL_CREATE_FORM',
                HIDE_THUMBNAIL_CREATE_FORM: 'HIDE_THUMBNAIL_CREATE_FORM',
                THUMBNAIL_CREATE_FORM_CANCEL: 'THUMBNAIL_CREATE_FORM_CANCEL',
                THUMBNAIL_CREATE_FORM_SUCCESS: 'THUMBNAIL_CREATE_FORM_SUCCESS',
                LOAD_SHEET_INTO_AGGREGATION_VIEWER: 'LOAD_SHEET_INTO_AGGREGATION_VIEWER',
                UNLOAD_SHEET_FROM_AGGREGATION_VIEWER: 'UNLOAD_SHEET_FROM_AGGREGATION_VIEWER',
                FILE_UPLOAD_PROGRESS: 'FILE_UPLOAD_PROGRESS',
                FILE_UPLOAD_SUCCESS: 'FILE_UPLOAD_SUCCESS',
                FILE_UPLOAD_FAILURE: 'FILE_UPLOAD_FAILURE'
            });
    }
});